package com.agamy.inventory.domain;

import static com.agamy.inventory.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SalePaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalePaymentAllPropertiesEquals(SalePayment expected, SalePayment actual) {
        assertSalePaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertSalePaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalePaymentAllUpdatablePropertiesEquals(SalePayment expected, SalePayment actual) {
        assertSalePaymentUpdatableFieldsEquals(expected, actual);
        assertSalePaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalePaymentAutoGeneratedPropertiesEquals(SalePayment expected, SalePayment actual) {
        assertThat(actual)
            .as("Verify SalePayment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalePaymentUpdatableFieldsEquals(SalePayment expected, SalePayment actual) {
        assertThat(actual)
            .as("Verify SalePayment relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalePaymentUpdatableRelationshipsEquals(SalePayment expected, SalePayment actual) {
        assertThat(actual)
            .as("Verify SalePayment relationships")
            .satisfies(a -> assertThat(a.getSale()).as("check sale").isEqualTo(expected.getSale()));
    }
}
